#!/bin/bash

set -e

if [ "$1" = "purge" ]; then
	userdel --remove --force gns3 2> /dev/null || true
	groupdel --force gns3 2> /dev/null || true
	rm -rf /var/lib/gns3 /var/log/gns3 /var/run/gns3
fi

#DEBHELPER#

exit 0
