#!/bin/bash

set -e

if [ "$1" = "configure" ]; then
	useradd --system --home /var/lib/gns3 --shell /usr/sbin/nologin gns3 || true
	chown -R gns3:gns3 /var/lib/gns3 || true
	chmod 0775 /var/lib/gns3 || true
	chmod 0660 /var/lib/gns3/gns3_server.conf || true
        for users in $(awk -F: '/\/home/ {printf "%s:%s\n",$1,$3}' /etc/passwd | cut -d: -f1)
        do
                usermod -a -G gns3 $users || true
        done
fi

#DEBHELPER#

exit 0
